apiVersion: v1
kind: Pod
metadata:
  name: cyclegan-data-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: sdsu-rci
    topology.kubernetes.io/region: us-west
  containers:
    - name: data-downloader
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/pytorch-CycleGAN-and-pix2pix
      command:
        - "bash"
        - "-c"
      args:
        - |
          # Install compression tools
          apt-get update && apt-get install -y zstd pv
          
          # Clone repository for data download script
          git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git ${REPO_PATH}
          cd ${REPO_PATH}
          
          pip install requests tqdm gdown 
          
          # Download horse2zebra dataset
          bash ./datasets/download_cyclegan_dataset.sh horse2zebra
          
          # Compress dataset to PVC
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          tar -cf - datasets/ | pv | zstd -19 -T$(nproc) > /data/cyclegan_dataset_${TIMESTAMP}.tar.zst
          
          # Verify and cleanup
          zstd -t /data/cyclegan_dataset_${TIMESTAMP}.tar.zst
          
          ls -lh /data/
          
          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: data-volume
          mountPath: /data
      resources:
        limits:
          memory: 12Gi
          cpu: "6"
        requests:
          memory: 10Gi
          cpu: "5"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: data-volume
      persistentVolumeClaim:
        claimName: cyclegan-data-pvc
  restartPolicy: Never