apiVersion: v1
kind: Pod
metadata:
  name: cyclegan-data-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: sdsu-rci
    topology.kubernetes.io/region: us-west
  containers:
    - name: data-downloader
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/pytorch-CycleGAN-and-pix2pix
      command:
        - "bash"
        - "-c"
      args:
        - |
          echo "Data download pod started"
          
          # Clone repository for dataset scripts
          git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git ${REPO_PATH}
          cd ${REPO_PATH}
          
          # Install minimal requirements
          pip install requests tqdm
          
          echo "Connect with: kubectl exec -it cyclegan-data-pod -- bash"
          echo "Then run: bash ./datasets/download_cyclegan_dataset.sh horse2zebra"
          echo "Copy to storage: mkdir -p /data/datasets && cp -r ./datasets/* /data/datasets/"
          
          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: data-volume
          mountPath: /data
      resources:
        limits:
          memory: 12Gi
          cpu: "6"
        requests:
          memory: 10Gi
          cpu: "5"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: data-volume
      persistentVolumeClaim:
        claimName: cyclegan-data-pvc
  restartPolicy: Never