apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyclegan-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: linstor-sdsu