apiVersion: v1
kind: Pod
metadata:
  name: cyclegan-train-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: sdsu-rci
    topology.kubernetes.io/region: us-west
  containers:
    - name: cyclegan-trainer
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/pytorch-CycleGAN-and-pix2pix
      command:
        - "bash"
        - "-c"
      args:
        - |
          echo "Training pod started"
          
          # Clone repository
          git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git ${REPO_PATH}
          cd ${REPO_PATH}
          
          # Install requirements
          pip install -r requirements.txt
          
          # Check for data
          if [ -d "/data/datasets" ]; then
            echo "Found datasets in /data/datasets"
            ls -la /data/datasets/
          else
            echo "No datasets found - run data_pod.yml first"
          fi
          
          echo ""
          echo "Training environment ready"
          echo "Connect with: kubectl exec -it cyclegan-train-pod -- bash"
          echo ""
          echo "Example training command:"
          echo "  python train.py --dataroot /data/datasets/horse2zebra --name test_run --model cycle_gan --n_epochs 5"
          echo ""
          
          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        requests:
          memory: 20Gi
          cpu: "10"
          nvidia.com/gpu: "1"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: data-volume
      persistentVolumeClaim:
        claimName: cyclegan-data-pvc
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  restartPolicy: Never