apiVersion: v1
kind: Pod
metadata:
  name: cyclegan-train-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: sdsu-rci
    topology.kubernetes.io/region: us-west
  containers:
    - name: cyclegan-trainer
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/pytorch-CycleGAN-and-pix2pix
      command:
        - "bash"
        - "-c"
      args:
        - |
          # Install decompression tools
          apt-get update && apt-get install -y zstd pv
          
          # Clone repository
          git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git ${REPO_PATH}
          cd ${REPO_PATH}
          
          # Install requirements
          pip install -r requirements.txt
          
          # Extract compressed data
          LATEST_DATASET=$(ls -t /data/cyclegan_dataset_*.tar.zst 2>/dev/null | head -1)
          if [ -n "$LATEST_DATASET" ]; then
            pv "$LATEST_DATASET" | zstd -d | tar -xf - -C ${REPO_PATH}/
            echo "Dataset extracted to ${REPO_PATH}/datasets/"
          elif [ -d "/data/datasets" ]; then
            echo "Using legacy datasets in /data/datasets"
          else
            echo "No datasets found - run data_pod.yml first"
          fi
          
          echo "Training environment ready"
          python train.py --dataroot ${REPO_PATH}/datasets/horse2zebra --name test_run --model cycle_gan --n_epochs 5
          
          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        requests:
          memory: 20Gi
          cpu: "10"
          nvidia.com/gpu: "1"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: data-volume
      persistentVolumeClaim:
        claimName: cyclegan-data-pvc
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  restartPolicy: Never